// GENERATED by scripts/part-stats.mjs — do not edit by hand. Re-run `npm run part-stats`
// after adding or removing a question in data.ts.
//
// Questions per subject in data.ts, for the Home page's subject buttons.

import type { SubjectId } from './subjects'

export const QUESTION_COUNT: Record<SubjectId, number> = {
  specialist: 391,
  methods: 402,
  chemistry: 73,
}
