// 2020 Chemistry Exam, MCQ 9. VCAA examination report: 28% correct. Calculating a solution
// calorimeter's calibration factor from an electrical calibration graph, using the plateau
// temperature rather than the reading at the moment the current stopped. Question text and
// graph transcribed from the original paper. Solution is original.

import Chem from '../Chem'
import { MCQShell } from '../MCQShell'
import type { WorkingRow, MCQExaminerStats } from '../QuestionParts'

const GRAPH = (
  <svg viewBox="0 0 260 170" className="w-full max-w-[280px]">
    <line x1="35" y1="150" x2="245" y2="150" stroke="currentColor" strokeWidth="1" className="text-gray-400" />
    <line x1="35" y1="150" x2="35" y2="15" stroke="currentColor" strokeWidth="1" className="text-gray-400" />
    {[17, 18, 19, 20, 21, 22].map((t, i) => (
      <text key={t} x="10" y={150 - i * 24 + 3} fontSize="9" className="fill-gray-500 dark:fill-gray-400">{t}</text>
    ))}
    <text x="120" y="163" fontSize="9" className="fill-gray-500 dark:fill-gray-400">time (s)</text>
    <path
      d="M 35 126 L 60 126 Q 90 126 110 100 Q 135 78 160 60 Q 180 45 200 32 Q 215 26 245 27"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      className="text-sky-600 dark:text-sky-400"
    />
    <line x1="35" y1="27" x2="245" y2="27" strokeDasharray="3,2" stroke="currentColor" strokeWidth="1" className="text-gray-400" />
    <text x="200" y="20" fontSize="10" className="fill-gray-600 dark:fill-gray-300">21.2 °C plateau</text>
  </svg>
)

const EXAMINER: MCQExaminerStats = {
  percentages: { A: 7, B: 28, C: 29, D: 35 },
  answer: 'B',
  comment: (
    <>
      The temperature continues to rise to 21.2 °C — a more accurate indicator of the thermal
      energy generated by the current flow than the reading at the moment the current was
      stopped.
    </>
  ),
}

const ROWS: WorkingRow[] = [
  {
    working: GRAPH,
    reason: <>Current was applied from 60 s to 240 s; the temperature keeps <i>rising</i> after 240 s before finally levelling off at 21.2 °C — heat takes time to fully mix through the water.</>,
  },
  {
    working: <Chem eq="Calibration factor = Electrical Energy / Change in temperature = VIt / T" />,
    reason: 'Formula relating the known electrical energy input to the resulting temperature rise.',
  },
  {
    working: <Chem eq="T = 21.2 - 18.0 = 3.2" className="mr-1" />,
    reason: <>Use the true plateau temperature (21.2 °C), <i>not</i> the ≈21.1 °C reading right when the current stopped — the system hadn't finished equilibrating yet.</>,
  },
  {
    working: (
      <>
        <span className="block">Calibration factor = (5.4 × 2.7 × 180) / 3.2</span>
        <span className="block">= 2624 J / 3.2 °C</span>
      </>
    ),
    reason: <>Substitute <Chem eq="V=5.4" /> V, <Chem eq="I=2.7" /> A, <Chem eq="t=180" /> s.</>,
  },
  {
    working: <b>= 820 J °C⁻¹</b>,
    reason: <>Matches option <b>B</b>. (Using the premature ΔT = 3.1 °C instead gives 847 J °C⁻¹, option C — a common but less accurate reading of the graph.)</>,
  },
]

export default function ChemistryQ9_2020() {
  return (
    <MCQShell
      question={
        <>
          <p className="mb-2">
            A solution calorimeter containing 350 mL of water was calibrated electrically. The
            current was 2.7 A, applied for 180 s starting at t = 60 s, at a voltage of 5.4 V. The
            temperature-vs-time graph of the calibration is shown below.
          </p>
          <div className="mb-3">{GRAPH}</div>
          <p>What is the calibration factor for this calorimeter?</p>
        </>
      }
      diagram={GRAPH}
      options={[
        { letter: 'A', content: '125 J °C⁻¹' },
        { letter: 'B', content: '820 J °C⁻¹', isAnswer: true },
        { letter: 'C', content: '847 J °C⁻¹' },
        { letter: 'D', content: '875 J °C⁻¹' },
      ]}
      rows={ROWS}
      examinerReport={EXAMINER}
    />
  )
}
