// 2020 Chemistry Exam, MCQ 9. VCAA examination report: 28% correct. Calculating a solution
// calorimeter's calibration factor from an electrical calibration graph, using the plateau
// temperature rather than the reading at the moment the current stopped. Question text
// transcribed from the original paper; the graph is cropped directly from the original VCAA
// exam PDF, not a redrawing. Solution is original.

import Chem from '../Chem'
import { MCQShell } from '../MCQShell'
import type { WorkingRow, MCQExaminerStats } from '../QuestionParts'
import graphSrc from './chem-2020-mcq9-calibration-graph.png'

const GRAPH = <img src={graphSrc} alt="Graph of temperature versus time during electrical calibration of the solution calorimeter, plateauing at 21.2 °C, from the original 2020 VCAA exam paper" className="w-full max-w-[420px]" />

const EXAMINER: MCQExaminerStats = {
  percentages: { A: 7, B: 28, C: 29, D: 35 },
  answer: 'B',
  comment: (
    <>
      The temperature continues to rise to 21.2 °C — a more accurate indicator of the thermal
      energy generated by the current flow than the reading at the moment the current was
      stopped.
    </>
  ),
}

const ROWS: WorkingRow[] = [
  {
    working: GRAPH,
    reason: <>Current was applied from 60 s to 240 s; the temperature keeps <i>rising</i> after 240 s before finally levelling off at 21.2 °C — heat takes time to fully mix through the water.</>,
  },
  {
    working: <Chem eq="Calibration factor = Electrical Energy / Change in temperature = VIt / T" />,
    reason: 'Formula relating the known electrical energy input to the resulting temperature rise.',
  },
  {
    working: <Chem eq="T = 21.2 - 18.0 = 3.2" className="mr-1" />,
    reason: <>Use the true plateau temperature (21.2 °C), <i>not</i> the ≈21.1 °C reading right when the current stopped — the system hadn't finished equilibrating yet.</>,
  },
  {
    working: (
      <>
        <span className="block">Calibration factor = (5.4 × 2.7 × 180) / 3.2</span>
        <span className="block">= 2624 J / 3.2 °C</span>
      </>
    ),
    reason: <>Substitute <Chem eq="V=5.4" /> V, <Chem eq="I=2.7" /> A, <Chem eq="t=180" /> s.</>,
  },
  {
    working: <b>= 820 J °C⁻¹</b>,
    reason: <>Matches option <b>B</b>. (Using the premature ΔT = 3.1 °C instead gives 847 J °C⁻¹, option C — a common but less accurate reading of the graph.)</>,
  },
]

export default function ChemistryQ9_2020() {
  return (
    <MCQShell
      question={
        <>
          <p className="mb-2">
            A solution calorimeter containing 350 mL of water was calibrated electrically. The
            current was 2.7 A, applied for 180 s starting at t = 60 s, at a voltage of 5.4 V. The
            temperature-vs-time graph of the calibration is shown below.
          </p>
          <p>What is the calibration factor for this calorimeter?</p>
        </>
      }
      diagram={GRAPH}
      options={[
        { letter: 'A', content: '125 J °C⁻¹' },
        { letter: 'B', content: '820 J °C⁻¹', isAnswer: true },
        { letter: 'C', content: '847 J °C⁻¹' },
        { letter: 'D', content: '875 J °C⁻¹' },
      ]}
      rows={ROWS}
      examinerReport={EXAMINER}
    />
  )
}
