// 2023 Specialist Mathematics — Exam 2, MCQ 11. VCAA examination report: 46% correct.
// Setting up the surface-of-revolution integral for y = cos⁻¹(x) about the y-axis. Question
// text transcribed from the original paper. Solution is original.

import Katex from '../../../components/Katex'
import { MCQShell } from '../MCQShell'
import type { WorkingRow, MCQExaminerStats } from '../QuestionParts'

const EXAMINER: MCQExaminerStats = {
  percentages: { A: 8, B: 6, C: 22, D: 18, E: 46 },
  answer: 'E',
}

const ROWS: WorkingRow[] = [
  {
    working: <Katex display tex="y = \cos^{-1}(x) \;\implies\; x = \cos(y),\quad y\in\big[0,\tfrac{\pi}{2}\big]" />,
    reason: <>Revolving about the <Katex tex="y" />-axis is easiest with <Katex tex="x" /> written as a function of <Katex tex="y" />.</>,
  },
  {
    working: <Katex display tex="S = 2\pi\int x\sqrt{1+\left(\frac{dx}{dy}\right)^2}\,dy" />,
    reason: 'Surface-of-revolution formula about the y-axis, integrating with respect to y.',
  },
  {
    working: <Katex display tex="\frac{dx}{dy} = -\sin(y) \;\implies\; 1+\left(\frac{dx}{dy}\right)^2 = 1+\sin^2(y)" />,
    reason: 'Differentiate x = cos(y).',
  },
  {
    working: <Katex display tex="S = 2\pi\int_0^{\pi/2} \cos(y)\sqrt{1+\sin^2(y)}\,dy" />,
    reason: <>Substitute in <Katex tex="x=\cos(y)" /> and the limits <Katex tex="y=0" /> to <Katex tex="y=\tfrac{\pi}{2}" /> (matching the given endpoints).</>,
  },
  {
    working: <Katex display tex="u=\sin(y) \;\implies\; du = \cos(y)\,dy" />,
    reason: <>Substitute — conveniently, the leading <Katex tex="\cos(y)" /> factor becomes exactly <Katex tex="du" />.</>,
  },
  {
    working: <Katex display tex="\boxed{S = 2\pi\int_0^1\sqrt{1+u^2}\,du}" />,
    reason: <>Limits become <Katex tex="u=\sin(0)=0" /> to <Katex tex="u=\sin(\pi/2)=1" /> — matches option <b>E</b>.</>,
  },
]

export default function SpecialistQ11_2023() {
  return (
    <MCQShell
      question={
        <p>
          The area of the curved surface generated by revolving part of the curve with equation{' '}
          <Katex tex="y=\cos^{-1}(x)" /> from <Katex tex="\big(0,\tfrac{\pi}{2}\big)" /> to <Katex tex="(1,0)" /> about
          the <Katex tex="y" />-axis can be found by evaluating
        </p>
      }
      options={[
        { letter: 'A', content: <Katex tex="2\pi\displaystyle\int_0^{\pi/2}\cos^{-1}(x)\sqrt{1+\dfrac{1}{x^2-1}}\,dx" /> },
        { letter: 'B', content: <Katex tex="2\pi\displaystyle\int_0^1\cos^{-1}(x)\sqrt{1+\dfrac{1}{x^2-1}}\,dx" /> },
        { letter: 'C', content: <Katex tex="2\pi\displaystyle\int_0^{\pi/2}\cos(y)\sqrt{1-\sin^2(y)}\,dy" /> },
        { letter: 'D', content: <Katex tex="2\pi\displaystyle\int_0^{\pi/2}\sqrt{1+u^2}\,du,\ \ u=\sin(y)" /> },
        { letter: 'E', content: <Katex tex="2\pi\displaystyle\int_0^1\sqrt{1+u^2}\,du,\ \ u=\sin(y)" />, isAnswer: true },
      ]}
      rows={ROWS}
      examinerReport={EXAMINER}
    />
  )
}
