// Generates src/tools/worked-solutions/partStats.ts: for every short-answer question, its
// parts (letter + marks) and VCAA's average mark for each, read straight out of the question
// files. The sidebar uses it to list a question's parts and to show how hard a short-answer
// question was (average as a share of the marks available).
//
// Run after adding or editing a short-answer question:   npm run part-stats
//
// It reads, per question file registered in details.ts:
//   - each <PartCard letter="…" topic="…" marks={n} examinerReport={NAME} videoSrc={…}>, in
//     order (videoSrc marks a part with a recorded video walkthrough), or for a
//     single-part question the <SAExaminerReport stats={NAME} maxMarks={n} /> instead;
//   - each `const NAME: SAExaminerStats = { marks: [...], average: x, ... }`.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'tools', 'worked-solutions')
const data = readFileSync(join(root, 'data.ts'), 'utf8')
const details = readFileSync(join(root, 'details.ts'), 'utf8')

const importOf = Object.fromEntries([...details.matchAll(/import (\w+) from '\.\/questions\/([\w.-]+)'/g)].map(m => [m[1], m[2]]))
const componentOf = Object.fromEntries([...details.matchAll(/'([\w-]+)':\s*(\w+),/g)].map(m => [m[1], m[2]]))
const saIds = [...data.matchAll(/\{ id: '([^']+)',[^\n]*?type: 'sa'/g)].map(m => m[1])

// The props of a JSX opening tag run to the first '>' outside any {…} expression.
function propsAfter(src, start) {
  let depth = 0
  for (let i = start; i < src.length; i++) {
    const ch = src[i]
    if (ch === '{') depth++
    else if (ch === '}') depth--
    else if (ch === '>' && depth === 0) return src.slice(start, i)
  }
  return ''
}

const out = {}
const problems = []
for (const id of saIds) {
  const file = importOf[componentOf[id]]
  if (!file) {
    problems.push(`${id}: no question file registered in details.ts`)
    continue
  }
  const src = readFileSync(join(root, 'questions', `${file}.tsx`), 'utf8')
  const averages = Object.fromEntries(
    [...src.matchAll(/const (\w+): SAExaminerStats = \{\s*marks: \[[^\]]*\],\s*average: ([\d.]+)/g)].map(m => [m[1], Number(m[2])]),
  )
  const parts = []
  for (const m of src.matchAll(/<PartCard\b/g)) {
    const props = propsAfter(src, m.index + m[0].length)
    const letter = props.match(/letter="([^"]+)"/)
    const marks = props.match(/marks=\{(\d+)\}/)
    const report = props.match(/examinerReport=\{(\w+)\}/)
    const topic = props.match(/\btopic="([^"]+)"/)
    if (!letter || !marks) continue
    const part = { l: letter[1], m: Number(marks[1]) }
    if (topic) part.t = topic[1]
    if (report && averages[report[1]] !== undefined) part.a = averages[report[1]]
    if (/\bvideoSrc=/.test(props)) part.v = true
    parts.push(part)
  }
  if (parts.length === 0) {
    const single = src.match(/<SAExaminerReport stats=\{(\w+)\} maxMarks=\{(\d+)\}/)
    if (single) {
      const part = { l: '', m: Number(single[2]) }
      if (averages[single[1]] !== undefined) part.a = averages[single[1]]
      parts.push(part)
    }
  }
  if (parts.length === 0) problems.push(`${id}: no parts or examiner report found in ${file}.tsx`)
  else if (parts.length > 1 && parts.some(p => !p.t)) problems.push(`${id}: a part has no topic="…" in ${file}.tsx`)
  else out[id] = parts
}

const body = Object.entries(out)
  .map(([id, parts]) => `  '${id}': ${JSON.stringify(parts).replace(/"(\w)":/g, '$1:')},`)
  .join('\n')

writeFileSync(
  join(root, 'partStats.ts'),
  `// GENERATED by scripts/part-stats.mjs — do not edit by hand. Re-run \`npm run part-stats\`
// after adding or editing a short-answer question.
//
// Per short-answer question: its parts in order — l = letter ('' for a single-part
// question), t = the part's subtopic (PartCard's topic), m = marks, a = VCAA's average mark
// (absent if the report has none), v = the part has a video walkthrough.

export interface PartStat {
  l: string
  t?: string
  m: number
  a?: number
  v?: true
}

export const PART_STATS: Record<string, PartStat[]> = {
${body}
}
`,
)

console.log(`partStats.ts: ${Object.keys(out).length} of ${saIds.length} short-answer questions`)
if (problems.length) console.log(`Skipped:\n  ${problems.join('\n  ')}`)
